### ISSUE TITLE
use js sdk v2

### ISSUE THREAD

**Issue by a5-pickle** [wormhole-foundation/example-liquidity-layer#41]
Found here: https://github.com/wormhole-foundation/wormhole-sdk-ts

**Comment by coderguy1998** [comment]
Should the @certusone/wormhole-sdk SDK be replaced by the above mentioned SDK and all the corresponding required changes? @a5-pickle

**Comment by a5-pickle** [comment]
Yes completely replacing the certusone lib would close this issue out.

**Comment by a5-pickle** [comment]
> Should the @certusone/wormhole-sdk SDK be replaced by the above mentioned SDK and all the corresponding required changes? @a5-pickle

Yes completely replacing the certusone lib would close this issue out.
